[project]
name = "polyshell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenneth Martin", email = "k.martin24@imperial.ac.uk" },
    { name = "Miriam North Ridao", email = "miriam.north-ridao15@imperial.ac.uk" },
    { name = "Niall Oswald", email = "niall.oswald20@imperial.ac.uk" },
    { name = "Jo Wayne Tan", email = "jo.tan17@imperial.ac.uk" },
]
requires-python = ">=3.12"
dependencies = [
    "rtree>=1.4.0",
]

[project.optional-dependencies]
cli = [
    "matplotlib>=3.10.3",
    "typer>=0.16.0",
]

[project.scripts]
polyshell = "polyshell.cli.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pyinstrument>=5.0.3",
    "pytest>=8.4.1",
    "pytest-cases>=3.9.1",
    "shapely>=2.1.1",
]

[tool.pyright]
typeCheckingMode = "strict"
